### ISSUE TITLE
market_melee | 535 Error 535 Authentication failed: Bad username / password | stack-trace

### ISSUE THREAD

**Issue by alexanderjsingleton** [alexanderjsingleton/melee#2]
@snuggs 

```
Net::SMTPAuthenticationError in Devise::RegistrationsController#create
535 Authentication failed: Bad username / password

Extracted source (around line #963):
961
962
963
964
965
966

    def check_auth_response(res)
      unless res.success?
        raise SMTPAuthenticationError, res.message
      end
    end


Rails.root: /Users/alexsingleton/Documents/Bloc/Checkpoints/code/melee

Application Trace | Framework Trace | Full Trace
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:963:in `check_auth_response'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:740:in `auth_plain'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:732:in `authenticate'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:567:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/smtp.rb:520:in `start'
mail (2.6.3) lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
mail (2.6.3) lib/mail/message.rb:2141:in `do_delivery'
mail (2.6.3) lib/mail/message.rb:236:in `block in deliver'
actionmailer (4.2.0) lib/action_mailer/base.rb:543:in `block in deliver_mail'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionmailer (4.2.0) lib/action_mailer/base.rb:541:in `deliver_mail'
mail (2.6.3) lib/mail/message.rb:236:in `deliver'
actionmailer (4.2.0) lib/action_mailer/message_delivery.rb:85:in `deliver_now'
devise (3.4.1) lib/devise/models/authenticatable.rb:176:in `send_devise_notification'
devise (3.4.1) lib/devise/models/confirmable.rb:102:in `send_confirmation_instructions'
devise (3.4.1) lib/devise/models/confirmable.rb:158:in `send_on_create_confirmation_instructions'
activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
activesupport (4.2.0) lib/active_support/callbacks.rb:225:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_create_callbacks'
activerecord (4.2.0) lib/active_record/callbacks.rb:306:in `_create_record'
activerecord (4.2.0) lib/active_record/timestamp.rb:57:in `_create_record'
activerecord (4.2.0) lib/active_record/persistence.rb:501:in `create_or_update'
activerecord (4.2.0) lib/active_record/callbacks.rb:302:in `block in create_or_update'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_save_callbacks'
activerecord (4.2.0) lib/active_record/callbacks.rb:302:in `create_or_update'
activerecord (4.2.0) lib/active_record/persistence.rb:120:in `save'
activerecord (4.2.0) lib/active_record/validations.rb:37:in `save'
activerecord (4.2.0) lib/active_record/attribute_methods/dirty.rb:21:in `save'
activerecord (4.2.0) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
activerecord (4.2.0) lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.0) lib/active_record/transactions.rb:220:in `transaction'
activerecord (4.2.0) lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
activerecord (4.2.0) lib/active_record/transactions.rb:286:in `block in save'
activerecord (4.2.0) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
activerecord (4.2.0) lib/active_record/transactions.rb:285:in `save'
devise (3.4.1) app/controllers/devise/registrations_controller.rb:19:in `create'
actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
actionpack (4.2.0) lib/action_dispatch/routing/mapper.rb:49:in `serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.1) lib/rack/etag.rb:24:in `call'
rack (1.6.1) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.1) lib/rack/head.rb:13:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.1) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
railties (4.2.0) lib/rails/engine.rb:518:in `call'
railties (4.2.0) lib/rails/application.rb:164:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
rack (1.6.1) lib/rack/content_length.rb:15:in `call'
rack (1.6.1) lib/rack/handler/webrick.rb:89:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
Request

Parameters:

{"utf8"=>"✓",
 "authenticity_token"=>"8JoyV61tCamOqIchuIf1qmTnyJ2DpK+J4yno+8EHO01n+e34rqKNdTFVsPg4QiHAj2k0T6juSNaK0z3RX21Lcg==",
 "user"=>{"name"=>"Alex Singleton",
 "email"=>"alexs_alias@gmail.com",
 "password"=>"[FILTERED]",
 "password_confirmation"=>"[FILTERED]"},
 "commit"=>"Sign up"}
Toggle session dump
Toggle env dump
Response

Headers:

None
>>   
```

**Comment by snuggs** [comment]
What are our thoughts on this link? http://stackoverflow.com/questions/25209676/running-into-smtp-error-when-trying-to-send-email-in-ror-app

**Comment by snuggs** [comment]
Ruby Send Grid gem. Let's try to test connection to Send Grid through it. 

https://github.com/sendgrid/sendgrid-ruby

**Comment by alexanderjsingleton** [comment]
```
027:0* puts client.send(mail)
SendGrid::Exception: {"message": "error", "errors": ["Bad username / password"]}
    from /Library/Ruby/Gems/2.0.0/gems/sendgrid-ruby-0.0.3/lib/sendgrid-ruby.rb:29:in `block in send'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:67:in `post'
    from /Library/Ruby/Gems/2.0.0/gems/sendgrid-ruby-0.0.3/lib/sendgrid-ruby.rb:24:in `send'
    from (irb):27
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Users/alexsingleton/Documents/Bloc/Checkpoints/code/melee/bin/rails:8:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'irb(main):028:0> # {"message":"success"}
irb(main):029:0*
irb(main):030:0*
irb(main):031:0* client = SendGrid::Client.new(api_user:'app36472752@heroku.com', api_key: 'jawcrx2o')
=> #<SendGrid::Client:0x007f89016e1310 @api_user="app36472752@heroku.com", @api_key="jawcrx2o", @host="https://api.sendgrid.com", @endpoint="/api/mail.send.json", @conn=#<RestClient::Resource:0x007f89016e1270 @url="https://api.sendgrid.com", @block=nil, @options={}>, @user_agent="sendgrid/0.0.3;ruby">
irb(main):032:0> mail = SendGrid::Mail.new do |m|
irb(main):033:1* m.to = 'snuggs_alias@gmail.com'
irb(main):034:1>  m.from = 'taco@cat.limo'
irb(main):035:1>   m.subject = 'Hello world!'
irb(main):036:1>   m.text = 'I heard you like pineapple.'
irb(main):037:1> end
=> #<SendGrid::Mail:0x007f89017118f8 @headers={}, @attachments=[], @smtpapi=#<Smtpapi::Header:0x007f8901711808 @to=[], @sub={}, @section={}, @category=[], @unique_args={}, @filters={}, @send_at=nil, @send_each_at=[], @asm_group_id=nil, @ip_pool=nil>, @to="rashaunstovoll@gmail.com", @from="taco@cat.limo", @subject="Hello world!", @text="I heard you like pineapple.">
irb(main):038:0>
irb(main):039:0* puts client.send(mail)
SendGrid::Exception: {"message": "error", "errors": ["Bad username / password"]}
    from /Library/Ruby/Gems/2.0.0/gems/sendgrid-ruby-0.0.3/lib/sendgrid-ruby.rb:29:in `block in send'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:493:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/rest-client-1.8.0/lib/restclient/resource.rb:67:in `post'
    from /Library/Ruby/Gems/2.0.0/gems/sendgrid-ruby-0.0.3/lib/sendgrid-ruby.rb:24:in `send'
    from (irb):39
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Users/alexsingleton/Documents/Bloc/Checkpoints/code/melee/bin/rails:8:in `<top (required)>'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in `<main>'irb(main):040:0> exit
```

**Comment by alexanderjsingleton** [comment]
Ok, issue closed.  In order to avoid compromising existing user authentication credentials for productions already deployed, instead of resetting, simply add a new credential to your Heroku Add-on SendGrid profile for your new application under development.   

My Solution:
1. Go to Heroku app dashboard.
2. Select "SendGrid" button underneath "Add-ons".
3. Upon direction to the Heroku SendGrid Add-ons page, go the right side of the page to "Account Overview" and select "Account Settings".
4. Upon direction to the "Account Settings" page, select "Manage Multiple User Credentials".
5. Upon direction to the "Manage Multiple User Credentials Page" select the "Add New Credential" button, which will prompt selection of "Web", "API" and "Mail options- enable all three and populate desired username and password, then finish action.
6. Enter the new credentials within corrpesponding "application.yml" file.
7. If using the Figaro gem to update your production environment variables, enter "figaro heroku:set -e production"; confirm changes with command "heroku config".
8. Test revision; attempt user sign-up-if successful, congrats!
9. Git add, commit changes on your local branch and merge into master; push to origin.
10. Deploy to Heroku.

Thanks again for the collaboration, @snuggs.

**Comment by snuggs** [comment]
Yeah buddy! Another one bites the dust. :+1:  :shipit: :ship: #SHIPIT @alexanderjsingleton !

**Comment by alexanderjsingleton** [comment]
👌👍👉 @snuggs
